version: '3.9'

services:
  userservice:
    image: userservice
    ports:
      - "5001:80"

  productservice:
    image: productservice
    ports:
      - "5002:80"

  orderservice:
    image: orderservice
    ports:
      - "5003:80"

  notificationservice:
    image: notificationservice
    ports:
      - "5004:80"

  paymentservice:
    image: paymentservice
    ports:
      - "5005:80"

  gatewayapi:
    image: gatewayapi
    ports:
      - "5000:80"
